version: '3.8'

services:
  media-service:
    build: .
    container_name: gazella-media-service
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - minio
      - rabbitmq
    networks:
      - gazella-net

  minio:
    image: minio/minio
    container_name: gazella-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - .env
    command: server /data --console-address ":9001"
    networks:
      - gazella-net

  rabbitmq:
    image: rabbitmq:3-management
    container_name: gazella-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - gazella-net

networks:
  gazella-net:
    external: true