services:
  media-service:
    build: .
    container_name: gazella-media-service
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - minio
    networks:
      - gazella-net

  minio:
    image: minio/minio
    container_name: gazella-minio
    ports:
      - "10000:9000"
      - "10001:9001"
    env_file:
      - .env
    command: server /data --console-address ":9001"
    networks:
      - gazella-net

networks:
  gazella-net:
    external: true